/**
 * Generic webhook dispatcher core: event model, durable pending-delivery
 * queue, signing, retry with backoff+jitter, delivery log, and replay.
 * `createWebhookDispatcher(namespace)` gives each plane its OWN isolated
 * event/queue/log state (so a sandbox tenant can never see or replay a
 * production event, and vice versa) while sharing every line of dispatch,
 * signing, and retry logic — see lib/sandbox/webhooks.ts and lib/webhooks.ts,
 * which are both thin instantiations of this factory.
 *
 * IN-REQUEST DISPATCH IS REJECTED BY DESIGN. A Vercel serverless function's
 * execution ends when its response is returned — code kicked off without an
 * `await` has no guarantee of ever finishing, so a fire-and-forget dispatch
 * inside the payment route can silently vanish. Awaiting it instead would
 * make the merchant's webhook endpoint latency (and downtime) part of our
 * own API response time, which is worse for every integrator than the
 * merchant's own reliability problem. So: emitEvent() only writes an
 * immutable event + a queued PendingDelivery row. Actual HTTP delivery
 * happens in drainPendingDeliveries(), invoked by a cron job (see
 * vercel.json "crons" and each plane's dispatch route). A real deployment
 * would use Vercel Workflow or a queue for sub-minute latency; a cron poll
 * is the documented stand-in here.
 */
import { randomUUID } from "node:crypto";
import { sign } from "../signature";
import type { WebhookEventType } from "./events";

export interface WebhookEvent {
  /** Immutable once created. Replays reuse this id verbatim — a fresh id would defeat idempotency testing. */
  id: string;
  apiKey: string;
  transactionId: string;
  type: string;
  /** Immutable snapshot — never mutated after creation, never regenerated by replay. */
  payload: Record<string, unknown>;
  createdAt: string;
}

export type DeliveryStatus = "PENDING" | "DELIVERED" | "DEAD_LETTERED";

export interface PendingDelivery {
  id: string;
  eventId: string;
  apiKey: string;
  url: string;
  attempt: number;
  maxAttempts: number;
  nextAttemptAt: string;
  status: DeliveryStatus;
  isReplay: boolean;
}

export interface DeliveryLogEntry {
  id: string;
  eventId: string;
  apiKey: string;
  url: string;
  attempt: number;
  httpStatus: number | null;
  error: string | null;
  sentAt: string;
  isReplay: boolean;
}

const MAX_ATTEMPTS = 6;
const BASE_BACKOFF_MS = 2_000;
const REPLAY_RATE_LIMIT_WINDOW_MS = 60_000;
const REPLAY_RATE_LIMIT_MAX = 10;

export class ReplayRateLimitedError extends Error {
  constructor(apiKey: string) {
    super(`Replay rate limit exceeded for ${apiKey}: max ${REPLAY_RATE_LIMIT_MAX} replays per ${REPLAY_RATE_LIMIT_WINDOW_MS / 1000}s`);
    this.name = "ReplayRateLimitedError";
  }
}

export class ReplayNotFoundError extends Error {
  constructor(eventId: string) {
    super(`No event ${eventId} found for this API key`);
    this.name = "ReplayNotFoundError";
  }
}

function backoffWithJitter(attempt: number): number {
  const exponential = BASE_BACKOFF_MS * 2 ** attempt;
  const jitter = Math.floor(Math.random() * BASE_BACKOFF_MS);
  return exponential + jitter;
}

export interface WebhookDispatcher {
  registerWebhookEndpoint(apiKey: string, url: string): void;
  getWebhookEndpoint(apiKey: string): string | undefined;
  emitEvent(apiKey: string, transactionId: string, type: WebhookEventType, payload: Record<string, unknown>, now?: Date): WebhookEvent;
  getEvent(eventId: string): WebhookEvent | undefined;
  drainPendingDeliveries(now?: Date, fetchImpl?: typeof fetch): Promise<{ attempted: number; delivered: number; deadLettered: number }>;
  replayDelivery(apiKey: string, eventId: string, now?: Date): PendingDelivery;
  listDeliveryLog(apiKey: string): DeliveryLogEntry[];
}

/** Each call creates an independent, isolated dispatcher — namespace is used only in the webhook signing secret env var lookup and for readability in logs. */
export function createWebhookDispatcher(namespace: "sandbox" | "production"): WebhookDispatcher {
  const events = new Map<string, WebhookEvent>();
  const endpoints = new Map<string, string>(); // apiKey -> webhook URL
  const queue: PendingDelivery[] = [];
  const log: DeliveryLogEntry[] = [];
  const replayCallLog = new Map<string, number[]>(); // apiKey -> recent replay call timestamps (ms)

  const signingSecret =
    namespace === "sandbox"
      ? (process.env.HOSCOO_WEBHOOK_SECRET ?? "hoscoo-local-dev-webhook-secret")
      : (process.env.HOSCOO_PRODUCTION_WEBHOOK_SECRET ?? process.env.HOSCOO_WEBHOOK_SECRET ?? "hoscoo-local-dev-webhook-secret");

  function checkReplayRateLimit(apiKey: string, now: Date): void {
    const history = (replayCallLog.get(apiKey) ?? []).filter((t) => now.getTime() - t < REPLAY_RATE_LIMIT_WINDOW_MS);
    if (history.length >= REPLAY_RATE_LIMIT_MAX) {
      replayCallLog.set(apiKey, history);
      throw new ReplayRateLimitedError(apiKey);
    }
    history.push(now.getTime());
    replayCallLog.set(apiKey, history);
  }

  return {
    registerWebhookEndpoint(apiKey, url) {
      endpoints.set(apiKey, url);
    },

    getWebhookEndpoint(apiKey) {
      return endpoints.get(apiKey);
    },

    emitEvent(apiKey, transactionId, type, payload, now = new Date()) {
      const event: WebhookEvent = { id: `hsc_evt_${randomUUID()}`, apiKey, transactionId, type, payload, createdAt: now.toISOString() };
      events.set(event.id, event);

      const url = endpoints.get(apiKey);
      if (url) {
        queue.push({ id: `hsc_del_${randomUUID()}`, eventId: event.id, apiKey, url, attempt: 0, maxAttempts: MAX_ATTEMPTS, nextAttemptAt: now.toISOString(), status: "PENDING", isReplay: false });
      }
      return event;
    },

    getEvent(eventId) {
      return events.get(eventId);
    },

    async drainPendingDeliveries(now = new Date(), fetchImpl = fetch) {
      const due = queue.filter((d) => d.status === "PENDING" && new Date(d.nextAttemptAt).getTime() <= now.getTime());
      let delivered = 0;
      let deadLettered = 0;

      for (const delivery of due) {
        const event = events.get(delivery.eventId);
        if (!event) {
          delivery.status = "DEAD_LETTERED";
          deadLettered++;
          continue;
        }

        const signature = sign(event.payload, signingSecret);
        let httpStatus: number | null = null;
        let error: string | null = null;

        try {
          const res = await fetchImpl(delivery.url, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "X-Hoscoo-Event-Id": event.id,
              "X-Hoscoo-Event-Type": event.type,
              "X-Hoscoo-Signature": signature,
              "X-Hoscoo-Replay": String(delivery.isReplay),
            },
            body: JSON.stringify(event.payload),
          });
          httpStatus = res.status;
          if (res.ok) {
            delivery.status = "DELIVERED";
            delivered++;
          } else {
            error = `HTTP ${res.status}`;
          }
        } catch (e) {
          error = e instanceof Error ? e.message : "Unknown delivery error";
        }

        log.push({ id: `hsc_log_${randomUUID()}`, eventId: event.id, apiKey: delivery.apiKey, url: delivery.url, attempt: delivery.attempt + 1, httpStatus, error, sentAt: now.toISOString(), isReplay: delivery.isReplay });

        if (delivery.status !== "DELIVERED") {
          delivery.attempt++;
          if (delivery.attempt >= delivery.maxAttempts) {
            delivery.status = "DEAD_LETTERED";
            deadLettered++;
          } else {
            delivery.nextAttemptAt = new Date(now.getTime() + backoffWithJitter(delivery.attempt)).toISOString();
          }
        }
      }

      return { attempted: due.length, delivered, deadLettered };
    },

    // Replay — re-delivery only. Callers (lib/sandbox/webhooks.ts's public
    // replay route) must never import ledger/simulation/quoteFx alongside
    // this function. See lib/sandbox/__tests__/replay-isolation.test.ts.
    replayDelivery(apiKey, eventId, now = new Date()) {
      checkReplayRateLimit(apiKey, now);

      const event = events.get(eventId);
      if (!event || event.apiKey !== apiKey) {
        throw new ReplayNotFoundError(eventId);
      }
      const url = endpoints.get(apiKey);
      if (!url) {
        throw new Error(`No webhook endpoint registered for ${apiKey}`);
      }

      const delivery: PendingDelivery = {
        id: `hsc_del_${randomUUID()}`,
        eventId: event.id, // same id, deliberately — never a fresh one.
        apiKey,
        url,
        attempt: 0,
        maxAttempts: MAX_ATTEMPTS,
        nextAttemptAt: now.toISOString(),
        status: "PENDING",
        isReplay: true,
      };
      queue.push(delivery);
      return delivery;
    },

    listDeliveryLog(apiKey) {
      return log.filter((l) => l.apiKey === apiKey);
    },
  };
}
